name: Test Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug username length
        run: |
          echo "Length: ${#USERNAME}"
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Validate Docker secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ] || [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "Docker secrets are not set!"
            exit 1
          fi

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/test-project:latest" .

      - name: Push image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/test-project:latest"

 # ⭐ ADD HERE — Deploy monitoring stack
      - name: Deploy monitoring stack
        run: |
          docker compose up -d


      # ⭐ NEW STEP — Send SMS Notification
      - name: Notify Deployment via SMS
        run: |
          curl -X POST OST https://61hgbriox2.execute-api.us-east-1.amazonaws.com/notify